#:schema node_modules/wrangler/config-schema.json
name = "podter-website"
compatibility_date = "2024-09-25"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "podter-website-test"
database_id = "3b9a6c45-6a54-45d9-87ad-64ec6458769e"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "c594175f8ada4f54b5a374158d2376af"
